language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:

    # Laravel 5.7
    - php: 7.2
      env: LARAVEL=5.7.* TESTBENCH=3.7.*
    - php: 7.3
      env: LARAVEL=5.7.* TESTBENCH=3.7.*

    # Laravel 5.8
    - php: 7.2
      env: LARAVEL=5.8.* TESTBENCH=3.8.*
    - php: 7.3
      env: LARAVEL=5.8.* TESTBENCH=3.8.*

before_install:
  - composer self-update --stable --no-interaction
  - composer require orchestra/testbench:$TESTBENCH phpunit/phpunit:^8.0 --no-update --no-interaction --dev
  - composer require friendsofphp/php-cs-fixer

install:
  - travis_retry composer install --no-suggest --no-interaction

script:
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - vendor/bin/phpunit --verbose --configuration phpunit.xml.dist