language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    # Laravel 5.8
    - php: 7.2
      env: LARAVEL=5.8.* TESTBENCH=3.8.* ORCHESTRA_DATABASE=3.8.* PHPUNIT=~8.0
    - php: 7.3
      env: LARAVEL=5.8.* TESTBENCH=3.8.* ORCHESTRA_DATABASE=3.8.* PHPUNIT=~8.0

before_install:
  - composer self-update --stable --no-interaction
  - composer require friendsofphp/php-cs-fixer

install:
  - travis_retry composer install --no-suggest --no-interaction

script:
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - vendor/bin/phpunit --verbose --configuration phpunit.xml.dist